# Generated by Django 2.0.4 on 2018-04-26 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eleicoes2018', '0002_auto_20180420_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='cargo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eleicoes2018.Cargo'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='estado_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eleicoes2018.Estado'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='partido_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eleicoes2018.Partido'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='estado_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eleicoes2018.Estado'),
        ),
        migrations.AlterField(
            model_name='voto',
            name='candidato_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eleicoes2018.Candidato'),
        ),
        migrations.AlterField(
            model_name='voto',
            name='cargo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eleicoes2018.Cargo'),
        ),
        migrations.AlterField(
            model_name='voto',
            name='usuario_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eleicoes2018.Usuario'),
        ),
    ]
