# Generated by Django 2.0.4 on 2018-04-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleicoes2018', '0003_auto_20180426_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='sigla',
            field=models.CharField(max_length=6),
        ),
    ]
