# Generated by Django 2.0.4 on 2018-04-27 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eleicoes2018', '0008_auto_20180427_2302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='usuario',
            new_name='user',
        ),
    ]
