# Generated by Django 2.0.4 on 2018-05-09 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eleicoes2018', '0013_remove_voto_cargo_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('candidato_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eleicoes2018.Candidato')),
            ],
        ),
    ]
