# Generated by Django 2.0.4 on 2018-05-15 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eleicoes2018', '0016_noticias'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Noticias',
            new_name='Noticia',
        ),
    ]
