# Generated by Django 2.0.4 on 2018-05-15 19:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleicoes2018', '0017_auto_20180515_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='data',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
