# Generated by Django 2.0.4 on 2018-05-28 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleicoes2018', '0018_noticia_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.IntegerField(max_length=11),
        ),
    ]
