# Generated by Django 2.0.4 on 2018-05-28 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eleicoes2018', '0022_auto_20180528_1953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidato',
            old_name='cargo_id',
            new_name='cargo',
        ),
        migrations.RenameField(
            model_name='candidato',
            old_name='estado_id',
            new_name='estado',
        ),
        migrations.RenameField(
            model_name='candidato',
            old_name='partido_id',
            new_name='partido',
        ),
        migrations.RenameField(
            model_name='info',
            old_name='candidato_id',
            new_name='candidato',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='estado_id',
            new_name='estado',
        ),
        migrations.RenameField(
            model_name='voto',
            old_name='candidato_id',
            new_name='candidato',
        ),
        migrations.RenameField(
            model_name='voto',
            old_name='usuario_id',
            new_name='usuario',
        ),
    ]
