# Generated by Django 2.0.4 on 2018-05-28 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleicoes2018', '0028_auto_20180528_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(max_length=11),
        ),
    ]
