# Generated by Django 2.0.4 on 2018-06-26 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eleicoes2018', '0030_candidato_votos_recebidos'),
        ('eleicoes2018', '0030_auto_20180626_1908'),
    ]

    operations = [
    ]
