# Generated by Django 2.0.4 on 2018-06-26 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eleicoes2018', '0031_merge_20180626_2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CargoBeneficio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eleicoes2018.Beneficio')),
            ],
        ),
        migrations.RemoveField(
            model_name='infocargo',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='votos_recebidos',
        ),
        migrations.AddField(
            model_name='cargo',
            name='descricao',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cargo',
            name='salario',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='InfoCargo',
        ),
        migrations.AddField(
            model_name='cargobeneficio',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eleicoes2018.Cargo'),
        ),
    ]
