# Generated by Django 2.0.4 on 2018-06-26 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleicoes2018', '0032_auto_20180626_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargobeneficio',
            name='valor',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
