# Generated by Django 2.0.4 on 2018-06-26 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleicoes2018', '0034_auto_20180626_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='descricao',
            field=models.CharField(max_length=800),
        ),
    ]
