# Generated by Django 2.0.4 on 2018-06-26 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleicoes2018', '0035_auto_20180626_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='salario',
            field=models.IntegerField(),
        ),
    ]
