# Generated by Django 2.0.4 on 2018-06-27 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eleicoes2018', '0036_auto_20180626_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localvotacao',
            name='local',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='local_votacao',
        ),
    ]
