# Generated by Django 2.0.4 on 2018-06-27 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleicoes2018', '0037_auto_20180627_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='localvotacao',
            name='mapa',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
